server:
  port: 8081


spring:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/money
    username: postgres
    password: password


  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.dialect.PostgreSQL81Dialect
